# Generated by Django 3.1.7 on 2021-03-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20210316_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, default='---', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
