# Generated by Django 3.1.7 on 2021-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20210316_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
