# Generated by Django 3.1.7 on 2021-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_auto_20210316_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
